#include <stdio.h>

int main(){
	short sa = 10, sb = -10;
	int ia = 80000, ib = -10;
	long la = 100000, lb = -10;
	long long lla = 12345678901, llb = -10;
	
	puts("sa:");
	printf("size: %d\n", sizeof(sa));
	printf("%%hd=%hd\n", sa);
	printf("%%d=%d\n", sa);
	printf("%%ld=%ld\n", sa);
	printf("%%lld=%lld\n", sa);
	printf("%%hu=%hu\n", sa);
	printf("%%u=%u\n", sa);
	printf("%%lu=%lu\n", sa);
	printf("%%llu=%llu\n", sa);
	puts("");
	puts("sb:");
	printf("size: %d\n", sizeof(sb));
	printf("%%hd=%hd\n", sb);
	printf("%%d=%d\n", sb);
	printf("%%ld=%ld\n", sb);
	printf("%%lld=%lld\n", sb);
	printf("%%hu=%hu\n", sb);
	printf("%%u=%u\n", sb);
	printf("%%lu=%lu\n", sb);
	printf("%%llu=%llu\n", sb);
	puts("");
	puts("ia:");
	printf("size: %d\n", sizeof(ia));
	printf("%%hd=%hd\n", ia);
	printf("%%d=%d\n", ia);
	printf("%%ld=%ld\n", ia);
	printf("%%lld=%lld\n", ia);
	printf("%%hu=%hu\n", ia);
	printf("%%u=%u\n", ia);
	printf("%%lu=%lu\n", ia);
	printf("%%llu=%llu\n", ia);
	puts("");
	puts("ib:");
	printf("size: %d\n", sizeof(ib));
	printf("%%hd=%hd\n", ib);
	printf("%%d=%d\n", ib);
	printf("%%ld=%ld\n", ib);
	printf("%%lld=%lld\n", ib);
	printf("%%hu=%hu\n", ib);
	printf("%%u=%u\n", ib);
	printf("%%lu=%lu\n", ib);
	printf("%%llu=%llu\n", ib);
	puts("");
	puts("la:");
	printf("size: %d\n", sizeof(la));
	printf("%%hd=%hd\n", la);
	printf("%%d=%d\n", la);
	printf("%%ld=%ld\n", la);
	printf("%%lld=%lld\n", la);
	printf("%%hu=%hu\n", la);
	printf("%%u=%u\n", la);
	printf("%%lu=%lu\n", la);
	printf("%%llu=%llu\n", la);
	puts("");
	puts("lb:");
	printf("size: %d\n", sizeof(lb));
	printf("%%hd=%hd\n", lb);
	printf("%%d=%d\n", lb);
	printf("%%ld=%ld\n", lb);
	printf("%%lld=%lld\n", lb);
	printf("%%hu=%hu\n", lb);
	printf("%%u=%u\n", lb);
	printf("%%lu=%lu\n", lb);
	printf("%%llu=%llu\n", lb);
	puts("");
	puts("lla:");
	printf("size: %d\n", sizeof(lla));
	printf("%%hd=%hd\n", lla);
	printf("%%d=%d\n", lla);
	printf("%%ld=%ld\n", lla);
	printf("%%lld=%lld\n", lla);
	printf("%%hu=%hu\n", lla);
	printf("%%u=%u\n", lla);
	printf("%%lu=%lu\n", lla);
	printf("%%llu=%llu\n", lla);
	puts("");
	puts("llb:");
	printf("size: %d\n", sizeof(llb));
	printf("%%hd=%hd\n", llb);
	printf("%%d=%d\n", llb);
	printf("%%ld=%ld\n", llb);
	printf("%%lld=%lld\n", llb);
	printf("%%hu=%hu\n", llb);
	printf("%%u=%u\n", llb);
	printf("%%lu=%lu\n", llb);
	printf("%%llu=%llu\n", llb);
	puts("");	
	return 0;
}
